var fs=require("fs")
fs.writeFileSync("B6.txt","Welcome Students")
// fs.mkdirSync("myFolder")
// fs.rmdirSync("myFolder")
var r=fs.readFileSync("B6.txt")
console.log(r.toString())
fs.appendFileSync("B6.txt","\nNode JS File System")
var r1=fs.readFileSync("B6.txt","utf-8")
console.log(r1)
fs.unlinkSync("B6.txt")
console.log("Completed")